
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - "8080:8080"
      # Uncomment the line below and set DEBUG=true to enable remote debugging
      - "5005:5005"
    networks:
      - nats
    depends_on:
      - redis
      - nats
    environment:
      SPRING_REDIS_HOST: ${REDIS_HOST}
      SPRING_REDIS_PORT: ${REDIS_PORT}
      SPRING_REDIS_PASSWORD: ${REDIS_PASSWORD:-redispassword}
      NATS_URL: ${NATS_URL}
      NATS_USER: ${NATS_USER:-natsuser}
      NATS_PASS: ${NATS_PASS:-natspassword}
      DEBUG: ${DEBUG:-false}

#  test:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      target: test
#    depends_on:
#      - redis
#      - nats
#    environment:
#      REDIS_HOST: redis
#      REDIS_PORT: 6379
#      NATS_URL: nats://nats:4222
#    networks:
#      - nats

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - nats
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redispassword}
    command: redis-server --requirepass ${REDIS_PASSWORD:-redispassword}

  nats:
    image: "nats:latest"
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - nats
    environment:
      NATS_USER: ${NATS_USER:-natsuser}
      NATS_PASS: ${NATS_PASS:-natspassword}
    command: ["-DV", "--http_port", "8222", "--trace", "--user", "$NATS_USER", "--pass", "$NATS_PASS"]

  nats-box:
    image: synadia/nats-box
    depends_on:
      - nats
    networks:
      - nats
    tty: true # Keep the container running

networks:
  nats:
