apiVersion: v1
kind: Service
metadata:
  name: secret-message
  labels:
    app.kubernetes.io/name: secret-message
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: secret-message
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 8080
      targetPort: http
